import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.scss';
import TaskForm from '@/components/TaskForm';
import { useState } from 'react';

console.log('hi');
export default function Home() {
  const [tasks, setTasks] = useState<string[]>([]);

  const handleAddTask = (task: string) => {
    setTasks([...tasks, task]);
  };

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <main>
        <div>
          <h1>Todo List</h1>
          <TaskForm onAddTask={handleAddTask} />
          <ul>
            {tasks.map(task => (
              <li key={task}>{task}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
